### ISSUE TITLE
Document haptic special function

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx-taranis-manual#1]
the value defines a pattern:
- 0 = 30ms vibe, 10ms pause, 10ms vibe
- 1 = 30ms vibe, 10ms pause, 10ms vibe, 40ms pause, 10ms vibe
- 2 = 30ms vibe, 10ms pause, 10ms vibe, 30ms pause, 10ms vibe, 30ms pause, 10ms vibe
- 3 = 30ms vibe, 10ms pause, 10ms vibe, 20ms pause, 10ms vibe, 20ms pause, 10ms vibe, 20ms pause, 10ms vibe

**Comment by powercycle** [comment]
This has been updated in the minor-edits branch and will be added as soon as that branch is merged with master.

Left issue open until merge is completed.

**Comment by projectkk2glider** [comment]
Thanks :+1:
