### ISSUE TITLE
SAR

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx-taranis-manual#12]
schwabe Admin 10:08 AM 
@rcdiy If you include this: A high SAR is just an indicator that the antenna broken. But a low value does not mean the antenna is fine. It is only an additional safeguard. Also some XJT modules are known to have broken SAR measurement and even with a removed antenna will have a low SAR.

Be careful with when modding your rf section. Even a good range is misleading as your antenna might be bad but the higher directional gain will mask that.

[QUOTE=Jet_Flyer;35914171]
The RAS number in OpenTX is the same as the SWR number in FrTX.  RAS is actually a name I came up with and it is Relative Antenna Status.  I suggested that name because it is not a true Standing Wave Ratio.  

The best way to use SWR or RAS is to note the normal number when you first get your system.   On both of my systems the normal is around 8 or 9 so I set my SWR alarm at 17.  That way if things degrade slowly I get an alarm and have some warning of a possible malfunction.   It will also give a instant warning if you select the external antenna without an antenna attached.  

During the development of FrTX there were a number of changes to the IJXT firmware to make the SWR number as meaningful as possible.  

Mike
[/QUOTE]

Kilrah Admin Owner 10:49 AM   
 
X7 module doesn't measure RAS

**Comment by powercycle** [comment]
This seems to imply that the SWR \ RAS is inconsistent or unreliable, although I do like the idea of issuing a warning if the antennae isn't attached.

**Comment by schwabe** [comment]
@powercycle yes, because it is. At least on X9D it is unreliable. Some models don't have a working SAR at all and X7D also has no working SAR.

And I would not fully trust it on the X12S as well.

**Comment by powercycle** [comment]
So, call this one closed?  Won't fix now?  @RCdiy, do you have additional thoughts?

**Comment by powercycle** [comment]
Let's re-open if more discussion is needed
