### ISSUE TITLE
Image Documentation X7 and other

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx-taranis-manual#22]
rcdiy 10:05 AM 
Does the X7 still not display greyscale images? I think that was what I was told. But I see that one can modify the splash/startup screem and it will use a grey scale image....

Kilrah Admin Owner 10:23 AM
the X7 screen does not support greyscale

rcdiy 10:34 AM   
How is it that the splash screen can be in grey scale? See https://youtu.be/Yy9IuJ5ZG5g?t=4m16s
YouTube 
Painless360 
Installing OpenTX 2.2 onto a Frsky Q X7 or other FrSky Radio (Taranis/Horus) 

How do we want to document this for the X7 i.e. splash screen?

Kilrah Admin Owner 10:35 AM
it's not greyscale, it's dithered black and white

rcdiy 10:36 AM
True.... I figured as much... but from a user point of view how do we document this?

schwabe Admin 10:37 AM   
Taranis Q X7: 1bit (only black and white) 128x64 bmp file
X9 family: 2 bit grayscale (black, ?% grey, ?% grey, white) Bitmap
not sure what the actual grayscale for x9 are

rcdiy 10:39 AM
do we mention anything about dithering? User's will see his grey scale I'd it would be nice to preempt that question.

schwabe Admin 10:43 AM 
sure you can add paragraph that mentiong that you can get grayscale like effects with dithering and that preparing the actual graphics is outside the scope of the manual

**Comment by powercycle** [comment]
@RCdiy , What would you like to do with this?   It seems like good info, but not sure what the intention is for it.
