### ISSUE TITLE
zadig documentation

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx-taranis-manual#24]

**Comment by RCdiy** [comment]
**Is Zadig required**

![bootloadersmall](https://user-images.githubusercontent.com/20209851/29190168-1b415e06-7de7-11e7-8d92-0010df929bbd.png)


| Tx  | OpenTX Boot Loader | PC OS | Add PC Driver |
| --- | ------------------- | ------  | ----------------------- |
| X7 | 2.2 | Any | No |
| X9D | 1.x | Windows | Zadig |
| X9D | 1.x | Linux | Dfu-util |
| X9D | 1.x | Mac | Dfu-util |
| X9D | 2.x | Any | No |
| X9D+ | 2.x | Any | No |
| X9E | 2.x | Any | No |
| X12S | 2.2 + later | Windows | Zadig |
| X12S | 2.2 + later| Linux | Dfu-util |
| X12S | 2.2 + later| Mac | Dfu-util |

MAC Note: Companion 2.2 for Mac comes with Dfu-util.

**Updating Boot Loader & Firmware**
- Writing firmware from Companion also updates the boot loader.
- Writing the firmware from OpenTX using bootloader mode updates both firmware and boot loader. Boot loader mode: Pull horizontal trims towards each other and tun on Tx.

**Updating Boot Loader Only** 
- Turning on the Tx, use SD Card browser, locate firmware, press ENT, flash boot loader..... this only changes the boot loader... firmware remains unchanged... useful if boot loader is bad or some other reason where you only want to change the boot loader but leave firmware as is.

**One Document**
Zadig documentation appears in more than one location. https://github.com/opentx/opentx/wiki/Taranis-Bootloaders
https://github.com/opentx/opentx-taranis-manual/blob/2.2/companion-introduction.md

Consolidate to just one?
The manual or the wiki... or we copy paste the exact same text and image of any. This will get out of sync however.

**Updating from OpenTX 1.x**
See http://open-txu.org/home/undergraduate-courses/fund-of-opentx/part-1-installing-opentx-companion/

**Janyary 17, 2017**
rcdiy 1:39 PM
It's been so long since I did the basics... Are Zadig and dfu-util still required assuming a new user?

Kilrah Admin Owner 2:42 PM
hasn't been for 2.5 years...

rcdiy 3:54 PM
Regardless of Tx age? So basically the operating systems now facilitate recognizing the Tx when plugged in?

Kilrah Admin Owner 3:57 PM
It's still dependent on what's running on the radio of course. Bootlaoder was introduced in 2.0 that long ago, now most people have updated since but of course some people won't have.
The break is that all Plus radios are for sure running 2.0. Older ones depend on whether the owner upgraded or not.

rcdiy 4:50 PM
So remove reference in docs?

**February 10, 2017**
rcdiy 12:23 PM 
Sometime ago I asked about Zadig and received an explanation. I've also read the wiki on this.
Question - Why am I seeing references to Zadig with Horus discussions. Why do they need to use the Tx STM Bootloader?
Which I believe is the only time Zadig is required.

Kilrah Admin Owner 12:28 PM
Only way to flash OpenTX on Horus

rcdiy 1:02 PM
Ah... TY...

**Comment by projectkk2glider** [comment]
I prefer to remove the wiki page. (And replace the contents with a link to the actual page in the manual) if you add/move the stuff to the manual.

**Comment by powercycle** [comment]
I agree with this, removing wiki page, move to manual.
Edit: Writing firmware from OpenTX bootloader mode only writes firmware.

**Comment by rdeanchurch** [comment]
I'm with the majority on removing Wiki.
In the document:
I would also suggest that the word Mode be replaced with Methods.  Modes to a newer user is going to suggest transmitter Modes.  
I'm trying to help a guy via email who is a Mode 1 user start his transition to QX7/OpenTx/Companion.  RcGroups and available videos had him thinking he had to install Zadig.  I hate that.

**Comment by powercycle** [comment]
@RCdiy are you intending to make a pull request for this?

**Comment by rdeanchurch** [comment]
It is a suggestion for consideration.  My intention was, if nobody but me thinks it is important, then it can be dismissed.
Would it be more appropriate it to make a pull request?  I'm not clear on the procedures for that.

**Comment by RCdiy** [comment]
@powercycle I have a pending pull request. #33 Once that is resolved I'll work on this.

@kilrah The wiki ( https://github.com/opentx/opentx/wiki/Taranis-Bootloaders ) will need to be update by an admin directly. Maybe place the following at the top on that page.

**Note: Do not install Zadig without first posting in a forum such as RCgroups OpenRCforums. Most transmitters no longer need Zadig.**

**Comment by RCdiy** [comment]
I submitted the documentation but the underlying structure on the files and headings were changed and now my work has to be re arranged... but we are getting there :) #35

**Comment by RCdiy** [comment]
@schwabe could you also fix the wiki? I don't have a way to do a pull request on that:)
Maybe place the following at the top on that page.

Note: Do not install Zadig without first posting in a forum such as RCgroups OpenRCforums. Most transmitters no longer need Zadig.

I think the content there is still relevant for the odd straggler (I'd say a single digit percentage of users?) that may need it...

**Comment by schwabe** [comment]
Well Zadiag is still important for windows for recovery from a bad firmware flash (i.e. wrong X9D/X9D+ firmware) or for the Horus. I will tackle this when I have time.

**Comment by RCdiy** [comment]
Put zadig in advanced/trouble shooting... the idea is that most people do not need it... the problem is people are installing in and then coming to the forums with problems... that was the reason for the suggestion on changing the explanation of zadig...

**Comment by RCdiy** [comment]
pull request #46
