### ISSUE TITLE
branch 2.2: images missing from companion section

### ISSUE THREAD

**Issue by powercycle** [opentx/opentx-taranis-manual#36]
Images are missing from companion section under these pages:

 - Basic Concepts
 - Setting up OpenTX Companion for Taranis
 - Flashing your FrSky radio

**Comment by RCdiy** [comment]
I added images but these sections are being redone as per #35

**Comment by powercycle** [comment]
OK, guess we can close this then?

**Comment by RCdiy** [comment]
suggest leaving it open. In the pull request I asked for this to be closed once that pull request is dealt with. Maybe review in a couple of weeks and close if images are fixed.

I also attached a bunch of images in a zip file in that pull request that could be used. While I was posting to my website I generated more images.

**Comment by powercycle** [comment]
This is closed by pull request: https://github.com/opentx/opentx-taranis-manual/pull/39
