### ISSUE TITLE
Basic Concepts - File Types

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx-taranis-manual#38]
Is this correct...

File Types

Companion handles different types of files:

**Firmware.bin** files which are non-editable and can be written to or copied from the radio. These files contain the radio's operating system.

**EEPROM.bin** files which can be edited, written to and read from the radio. These files contain the radio and model settings.

**EEPROM.otx** files are similar to the EEPROM.bin files but have been processed by Companion. An EEPROM.bin file, when on the computer, is a direct copy from the radio to the computer by companion. 

The explanation does not feel complete.... What does processed by companion mean in lay person terms?

**Comment by powercycle** [comment]
My belief is that it means the Companion software reads the bin file from the radio, parses it into values that Companion can use and understand.  

An OTX file is basically a zip file that contains MODELS and RADIO folders.  Within each of those are some files, the layout of which I believe is beyond the scope of the manual.

The EEPROM.bin file is basically a raw copy of the "memory" of the transmitter.

This is a bit of speculation on my part without some confirmation from a developer.

**Comment by schwabe** [comment]
@powercycle is basically correct. For Horus you have a file structure on the sd card and models are saved there. On the other radios you have a raw dump of the eeprom. Users should not try to edit/mess with these files.

In lay man term both are a dump/copy of the settings of the transmitter.
