### ISSUE TITLE
2.2.1 release notes/update documentation

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx-taranis-manual#59]
Things to check and update in documentation
Added FrSKY long range R9M external module mode options support
Added USB Mode to radio menu setup screen (Ask, Joystick, SDCard)
Added support for X10 series
Added sbus output to the external module bay
Added X7 rssi indicator bars like a cell phone
Added X7 new model wizard
Added/fixed missing X7 SQT5 font 
Added X7 Crossfire scripts
Added X7 Hardware screen baud speed for crossfire
Added X7 Lua draw bitmap
Added alert when trying to power off with a receiver connected (Radio menu setup screen)
Added preflight checklist editing to Companion Model Setup
Added a resettable total run time timer to statics screen (Long Press ENTER to reset/Press MENU then press ENTER to reset. )
Added disabling of telemetry warnings (telemetry screen)
Added a debug screen (on statistics screen press menu)
Added Portuguese sound files
SDcard version changed to 2.2V0011

**Comment by RCdiy** [comment]
@kilrah has x10 support been officially added for 2.2.1?

**Comment by kilrah** [comment]
Draft's already here: https://github.com/opentx/opentx.github.io/blob/3djc/2.2.1-prep/_posts/2017-11-24-opentx-2.2.1.md

**Comment by RCdiy** [comment]
How do we suggest edits to that writeup?

**Comment by RCdiy** [comment]
The zadig section seems to suggest that installing zadig was normal. It is not normal fir Taranis series.

**Comment by RCdiy** [comment]
This issue was opened as a placeholder to remember to update the manual. If the manual has not been updated then this should stay open.
