### ISSUE TITLE
Gitbook 2.2 manual: Amber sounds are for other transmitters also

### ISSUE THREAD

**Issue by RealTadango** [opentx/opentx-taranis-manual#9]
On this page: https://opentx.gitbooks.io/manual-for-opentx-2-2/content/advanced/add-ons.html it looks like the amber sound pack is Taranis only. It works on other (all??) OpenTX transmitters so a general section mentioning the sounds would be clearer.

Also (from @3djc ) :
- it doesn't specify that this is english only
- since the amber pack download does not specify compatible sdcard version number, unsure it should be mentioned there

**Comment by powercycle** [comment]
So, move this to a "general" section and ensure that is specified as English only?  
Don't understand the part about SD card version number and compatible and not being mentioned there.

**Comment by 3djc** [comment]
What I was meaning is now that we have introduced a versioning for sdcard content, I personally think we should link only packs that make use it.

**Comment by powercycle** [comment]
@3djc , @schwabe suggested some changes in https://github.com/opentx/opentx-taranis-manual/pull/19/commits/13de3586208a9381ecb4d6a89da816626e7cd956.

Not sure if that covers everything for what you are referring to.

**Comment by schwabe** [comment]
I accidentally committed my fixes to the default branch but they should address this.

**Comment by powercycle** [comment]
So should this issue be closed?  If not, what is left to address?

**Comment by schwabe** [comment]
Should be fine now.
